### ISSUE TITLE
Running consecutive tests with different JSON fails

### ISSUE THREAD

**Issue by gevesson** [SpectoLabs/hoverfly-junit#10]
I am running two consecutive tests with different JSON. The second test fails unless I make it wait a couple of seconds for Hoverfly to complete exiting from the previous test.

**Comment by mogronalol** [comment]
Could you elaborate on what you mean by two consecutive tests please - do you mean two tests within the same class file, or two seperate class file?  Is the rule static? 

If you could post a code example it would be useful.  Thanks.

**Comment by mogronalol** [comment]
Closed due to inactivity
