### ISSUE TITLE
JVM Proxy settings are not respected by Apache Http Client

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly-junit#2]
This library does not respect these system properties by default

**Comment by mogronalol** [comment]
Looks like this has to be configured by the tests author.  It seems a bit bizarre that any Java http client library wouldn't respect these system properties by default, but maybe I am missing something.  I've updated the `readme` accordingly.  Thankfully it's only a tiny bit of code to get working.

**Comment by apex-ethanjohnson** [comment]
With the upgrade to Apache HttpClient 5 this solution no longer works. I am still trying to find a workaround...

**Comment by sharedprophet** [comment]
With the upgrade to Apache HttpClient 5.x this solution no longer works. I am looking for a fix...
