### ISSUE TITLE
SSLHandshakeException when using @Rule HoverflyRule in capture mode with HTTPS website

### ISSUE THREAD

**Issue by Dalamar42** [SpectoLabs/hoverfly-junit#24]
**Issue**
When running `HoverflyRule` in capture mode as a `@Rule` against an HTTPS website I am getting an `sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` exception.

However if I run the same rule as a `@ClassRule` it works and if I run the tests in sequence so that the `@ClassRule` test runs before the `@Rule` one it also works.

**Logs**
For the first scenario where only the `@Rule` test is run and it fails checked in the attached archive: `docs/running-rule-test-alone.log`

For the third scenario where the `@Rule` is run in sequence after the `@ClassRule` test check `docs/running-rule-test-after-classrule-test.log`

**Reproduction**
In the attached maven project:
- run `mvn test -Dtest=HoverflyEvaluatorRuleTest` to reproduce the failure
- run `mvn test` to reproduce the third scenario above

**OS** OSX El Capitan 10.11.6 (15G1108)
**HW** MacBook Pro (Retina, 15-inch, Mid 2015)
**Versions** 
- Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
- java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
- org.apache.httpcomponents:httpclient:4.5.2
- junit:junit:4.12
- io.specto:hoverfly-junit:0.2.2

**Attachments**
[hoverflytest.tar.gz](https://github.com/SpectoLabs/hoverfly-junit/files/659608/hoverflytest.tar.gz)

**Comment by Dalamar42** [comment]
@tommysitu Let me know if there is any more info that you think could help

**Comment by tommysitu** [comment]
@Dalamar42 I can see the problem now. When using @Rule, the hoverfly is started after the creation of the http client therefor the http client does not know the JVM system properties had been updated by hoverfly.

**Comment by tommysitu** [comment]
@Dalamar42 one workaround is to move the construction of object-under-test to setup method:
```
@Before
public void setUp() throws Exception {
    evaluator = HoverflyEvaluator.create();
}
```

Becuase `@Rule` is always executed before `@Before`.

**Comment by Dalamar42** [comment]
@tommysitu Right that makes sense. I can confirm it works with `@Before` (which is better practice anyway). Thanks for looking into this.

**Comment by tommysitu** [comment]
@Dalamar42 I've updated the README to give more instructions on using `HoverflyRule` with Apache `HttpClient`. I'd also recommend using `@ClassRule` whenever you can. It is more efficient by sharing Hoverfly server among your tests. It also guarantees that HoverflyRule fully configures the environment before your test fixtures.

**Comment by Dalamar42** [comment]
@tommysitu Makes sense. Cheers
